# Generated by Django 6.0.2 on 2026-05-14 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в фильтрах')),
                ('display_type', models.CharField(choices=[('single', 'Одиночное фото'), ('carousel', 'Карусель'), ('slider', 'Шторка (До/После)')], default='single', help_text='Используется как значение по умолчанию при создании новых карточек', max_length=20, verbose_name='Тип отображения по умолчанию')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа карточек',
                'verbose_name_plural': 'Группы карточек',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(blank=True, choices=[('single', 'Одиночное фото'), ('carousel', 'Карусель'), ('slider', 'Шторка (До/После)')], default='single', help_text='Выбирается индивидуально для каждой карточки (независимо от категории)', max_length=20, null=True, verbose_name='Тип отображения фото')),
                ('photo', models.ImageField(blank=True, editable=False, null=True, upload_to='photos/', verbose_name='Фото (устарело)')),
                ('full_text', models.TextField(verbose_name='Текст для копирования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_cards', to='content.category', verbose_name='Категория')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='content.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/multiple/%Y/%m/%d/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.contentitem', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Фото карточки',
                'verbose_name_plural': 'Фото карточек',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.category', verbose_name='Верхнеуровневая категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='groups', to='content.subcategory', verbose_name='Подкатегории в группе'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='content.subcategory', verbose_name='Подкатегория'),
        ),
    ]
