# Generated by Django 6.0.2 on 2026-05-15 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='photo',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='video',
            field=models.FileField(blank=True, help_text='Рекомендуемый формат: MP4 (H.264). Макс. размер — 50 МБ', null=True, upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])], verbose_name='Видео файл'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='videos/posters/%Y/%m/%d/', verbose_name='Постер для видео (превью)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_type',
            field=models.CharField(choices=[('single', 'Одиночное фото'), ('carousel', 'Карусель'), ('slider', 'Шторка (До/После)'), ('video', 'Видео')], default='single', help_text='Используется как значение по умолчанию при создании новых карточек', max_length=20, verbose_name='Тип отображения по умолчанию'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='display_type',
            field=models.CharField(choices=[('single', 'Одиночное фото'), ('carousel', 'Карусель'), ('slider', 'Шторка (До/После)'), ('video', 'Видео')], default='single', help_text='Выбирается индивидуально для каждой карточки (независимо от категории)', max_length=20, verbose_name='Тип отображения фото'),
        ),
    ]
