# Generated by Django 6.0.2 on 2026-04-28 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_fill_categories_and_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_cards', to='content.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='content.group', verbose_name='Группа'),
        ),
    ]
