# Generated by Django 6.0.2 on 2026-05-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_video_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='video',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='video_poster',
        ),
        migrations.AlterField(
            model_name='category',
            name='display_type',
            field=models.CharField(choices=[('single', 'Одиночное фото'), ('carousel', 'Карусель'), ('slider', 'Шторка (До/После)')], default='single', help_text='Используется как значение по умолчанию при создании новых карточек', max_length=20, verbose_name='Тип отображения по умолчанию'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='display_type',
            field=models.CharField(choices=[('single', 'Одиночное фото'), ('carousel', 'Карусель'), ('slider', 'Шторка (До/После)')], default='single', help_text='Выбирается индивидуально для каждой карточки (независимо от категории)', max_length=20, verbose_name='Тип отображения фото'),
        ),
    ]
