# Generated by Django 6.0.2 on 2026-05-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_migrate_display_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='display_type',
            field=models.CharField(choices=[('single', 'Одиночное фото'), ('carousel', 'Карусель'), ('slider', 'Шторка (До/После)')], default='single', help_text='Выбирается индивидуально для каждой карточки (независимо от категории)', max_length=20, verbose_name='Тип отображения фото'),
        ),
    ]
