# Generated by Django 6.0.2 on 2026-05-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contentitem_category_alter_contentitem_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='photo',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='photos/', verbose_name='Фото (устарело)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='groups', to='content.subcategory', verbose_name='Подкатегории в группе'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='ContentItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/multiple/%Y/%m/%d/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.contentitem', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Фото карточки',
                'verbose_name_plural': 'Фото карточек',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CopyLog',
        ),
    ]
