# Generated by Django 6.0.2 on 2026-05-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_make_display_type_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='photo',
        ),
    ]
