# Generated by Django 6.0.2 on 2026-05-16 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_cleanup_contentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='Видео файл')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='videos/posters/%Y/%m/%d/', verbose_name='Постер (превью)')),
                ('prompt_description', models.TextField(verbose_name='Описание промпта (для отображения)')),
                ('copy_text', models.TextField(verbose_name='Текст для копирования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cards', to='content.category', verbose_name='Категория')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_cards', to='content.group', verbose_name='Группа')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cards', to='content.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Видео-карточка',
                'verbose_name_plural': 'Видео-карточки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoCardReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='videos/references/%Y/%m/%d/', verbose_name='Референсное фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('video_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='content.videocard', verbose_name='Видео-карточка')),
            ],
            options={
                'verbose_name': 'Референс видео-карточки',
                'verbose_name_plural': 'Референсы видео-карточек',
                'ordering': ['order'],
            },
        ),
    ]
