# Generated by Django 6.0.2 on 2026-05-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_category_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_type',
            field=models.CharField(choices=[('single', 'Одиночное фото'), ('carousel', 'Карусель'), ('slider', 'Шторка (До/После)')], default='single', max_length=20, verbose_name='Тип отображения карточек'),
        ),
    ]
